# Generated by Django 3.2 on 2023-03-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
