# Generated by Django 3.2 on 2023-03-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0004_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('msg', models.CharField(max_length=500, verbose_name='message')),
            ],
        ),
    ]
