# Generated by Django 3.2 on 2023-03-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='msg',
            field=models.TextField(max_length=500, verbose_name='message'),
        ),
    ]
