# Generated by Django 3.2 on 2023-03-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0007_auto_20230314_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='allProduct',
        ),
    ]
