# Generated by Django 3.2 on 2023-03-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0008_rename_product_allproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproduct',
            name='catergory',
        ),
    ]
