# Generated by Django 3.2 on 2023-03-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0009_remove_allproduct_catergory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allProduct',
            new_name='Product',
        ),
    ]
