# Generated by Django 3.2 on 2023-04-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0012_auto_20230314_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_addr', models.CharField(max_length=100)),
                ('user_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
