# Generated by Django 3.2 on 2023-04-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0013_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrendNow.user_login')),
                ('product_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrendNow.product')),
            ],
        ),
    ]
