# Generated by Django 3.2 on 2023-04-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0014_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='created_d_t',
        ),
    ]
