# Generated by Django 3.2 on 2023-04-01 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0022_auto_20230401_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_d_t',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 20, 5, 9, 938540)),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_d_t', models.DateTimeField(default=datetime.datetime(2023, 4, 1, 20, 5, 9, 938540))),
                ('loged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrendNow.user_login')),
                ('product_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrendNow.product')),
            ],
        ),
    ]
