# Generated by Django 4.1.7 on 2023-04-04 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0023_auto_20230401_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_d_t',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 0, 2, 31, 688214)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_qty',
            field=models.IntegerField(blank=True, default='1', null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrendNow.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_d_t',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 5, 0, 2, 31, 688214), null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='loged_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrendNow.user_login'),
        ),
        migrations.CreateModel(
            name='user_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name ')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name ')),
                ('user_email', models.CharField(max_length=500, verbose_name='Email ')),
                ('user_addr', models.CharField(max_length=500, verbose_name='address')),
                ('city', models.CharField(max_length=500, verbose_name='City')),
                ('country', models.CharField(max_length=500, verbose_name='Country')),
                ('zipcode', models.CharField(max_length=500, verbose_name='Zip Code')),
                ('telephone', models.CharField(max_length=500, verbose_name='Telephone')),
                ('total_price', models.FloatField(max_length=5000, verbose_name='Total Price')),
                ('payment_mode', models.CharField(max_length=5000, verbose_name='Payment Mode')),
                ('payment_id', models.CharField(max_length=5000, null=True, verbose_name='Payment ID')),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Out of Shiping', 'out of shiping'), ('Completed', 'completed')], default='Pending', max_length=100, verbose_name='Status')),
                ('message', models.TextField(max_length=5000, verbose_name='Message')),
                ('tracking_no', models.CharField(max_length=5000, verbose_name='Tracing NO')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('loged_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrendNow.user_login', verbose_name='Login User Data ')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip Code')),
                ('created_dt', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 5, 0, 2, 31, 688214), null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TrendNow.user_login', verbose_name='User Data')),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('qty', models.IntegerField(blank=True, verbose_name='Quatity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrendNow.product', verbose_name='Product Order')),
            ],
        ),
    ]
