# Generated by Django 4.1.7 on 2023-04-04 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0026_alter_cart_created_d_t_alter_profile_created_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='product',
            new_name='user_product',
        ),
        migrations.AddField(
            model_name='order_item',
            name='user_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrendNow.user_order', verbose_name='Order Items'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_d_t',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 0, 20, 53, 600329)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 5, 0, 20, 53, 600329), null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_d_t',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 5, 0, 20, 53, 600329), null=True),
        ),
    ]
