# Generated by Django 4.1.7 on 2023-04-05 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrendNow', '0028_alter_cart_created_d_t_alter_profile_created_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='user_order',
            new_name='user_order_det',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_d_t',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 19, 24, 36, 28255)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 5, 19, 24, 36, 28255), null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_d_t',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 5, 19, 24, 36, 28255), null=True),
        ),
    ]
